// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.25.3
// source: messages.proto

package railway_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ETrainState int32

const (
	ETrainState_IN_TRIP    ETrainState = 0
	ETrainState_IN_QUEUE   ETrainState = 1
	ETrainState_ARRIVED    ETrainState = 2
	ETrainState_DEPARTURED ETrainState = 3
)

// Enum value maps for ETrainState.
var (
	ETrainState_name = map[int32]string{
		0: "IN_TRIP",
		1: "IN_QUEUE",
		2: "ARRIVED",
		3: "DEPARTURED",
	}
	ETrainState_value = map[string]int32{
		"IN_TRIP":    0,
		"IN_QUEUE":   1,
		"ARRIVED":    2,
		"DEPARTURED": 3,
	}
)

func (x ETrainState) Enum() *ETrainState {
	p := new(ETrainState)
	*p = x
	return p
}

func (x ETrainState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ETrainState) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (ETrainState) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x ETrainState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ETrainState.Descriptor instead.
func (ETrainState) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type Train struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Wagons     uint32      `protobuf:"varint,3,opt,name=wagons,proto3" json:"wagons,omitempty"`
	TrainState ETrainState `protobuf:"varint,4,opt,name=train_state,json=trainState,proto3,enum=GRPCRailway.ETrainState" json:"train_state,omitempty"`
}

func (x *Train) Reset() {
	*x = Train{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Train) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Train) ProtoMessage() {}

func (x *Train) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Train.ProtoReflect.Descriptor instead.
func (*Train) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Train) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Train) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Train) GetWagons() uint32 {
	if x != nil {
		return x.Wagons
	}
	return 0
}

func (x *Train) GetTrainState() ETrainState {
	if x != nil {
		return x.TrainState
	}
	return ETrainState_IN_TRIP
}

type RailwayState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RailNum uint32   `protobuf:"varint,1,opt,name=rail_num,json=railNum,proto3" json:"rail_num,omitempty"`
	Trains  []*Train `protobuf:"bytes,2,rep,name=trains,proto3" json:"trains,omitempty"`
}

func (x *RailwayState) Reset() {
	*x = RailwayState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RailwayState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RailwayState) ProtoMessage() {}

func (x *RailwayState) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RailwayState.ProtoReflect.Descriptor instead.
func (*RailwayState) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *RailwayState) GetRailNum() uint32 {
	if x != nil {
		return x.RailNum
	}
	return 0
}

func (x *RailwayState) GetTrains() []*Train {
	if x != nil {
		return x.Trains
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

var File_messages_proto protoreflect.FileDescriptor

var file_messages_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x47, 0x52, 0x50, 0x43, 0x52, 0x61, 0x69, 0x6c, 0x77, 0x61, 0x79, 0x22, 0x7e, 0x0a,
	0x05, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x61,
	0x67, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x77, 0x61, 0x67, 0x6f,
	0x6e, 0x73, 0x12, 0x39, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x52, 0x61,
	0x69, 0x6c, 0x77, 0x61, 0x79, 0x2e, 0x45, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x55, 0x0a,
	0x0c, 0x52, 0x61, 0x69, 0x6c, 0x77, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x72, 0x61, 0x69, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x72, 0x61, 0x69, 0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x2a, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x52,
	0x61, 0x69, 0x6c, 0x77, 0x61, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x06, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2a, 0x45, 0x0a,
	0x0b, 0x45, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x49, 0x4e, 0x5f, 0x54, 0x52, 0x49, 0x50, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x5f,
	0x51, 0x55, 0x45, 0x55, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x52, 0x52, 0x49, 0x56,
	0x45, 0x44, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x45, 0x50, 0x41, 0x52, 0x54, 0x55, 0x52,
	0x45, 0x44, 0x10, 0x03, 0x32, 0x83, 0x01, 0x0a, 0x07, 0x52, 0x61, 0x69, 0x6c, 0x77, 0x61, 0x79,
	0x12, 0x42, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x61, 0x69, 0x6c, 0x77, 0x61, 0x79, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x52, 0x61, 0x69, 0x6c, 0x77, 0x61,
	0x79, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x52, 0x61,
	0x69, 0x6c, 0x77, 0x61, 0x79, 0x2e, 0x52, 0x61, 0x69, 0x6c, 0x77, 0x61, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x12, 0x12, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x52, 0x61, 0x69, 0x6c, 0x77, 0x61, 0x79, 0x2e, 0x54,
	0x72, 0x61, 0x69, 0x6e, 0x1a, 0x12, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x52, 0x61, 0x69, 0x6c, 0x77,
	0x61, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x68, 0x74,
	0x74, 0x70, 0x5f, 0x72, 0x61, 0x69, 0x6c, 0x77, 0x61, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x72, 0x61, 0x69, 0x6c, 0x77, 0x61, 0x79, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData = file_messages_proto_rawDesc
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_proto_rawDescData)
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_messages_proto_goTypes = []interface{}{
	(ETrainState)(0),     // 0: GRPCRailway.ETrainState
	(*Train)(nil),        // 1: GRPCRailway.Train
	(*RailwayState)(nil), // 2: GRPCRailway.RailwayState
	(*Empty)(nil),        // 3: GRPCRailway.Empty
}
var file_messages_proto_depIdxs = []int32{
	0, // 0: GRPCRailway.Train.train_state:type_name -> GRPCRailway.ETrainState
	1, // 1: GRPCRailway.RailwayState.trains:type_name -> GRPCRailway.Train
	3, // 2: GRPCRailway.Railway.GetRailwayState:input_type -> GRPCRailway.Empty
	1, // 3: GRPCRailway.Railway.GetTrain:input_type -> GRPCRailway.Train
	2, // 4: GRPCRailway.Railway.GetRailwayState:output_type -> GRPCRailway.RailwayState
	1, // 5: GRPCRailway.Railway.GetTrain:output_type -> GRPCRailway.Train
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Train); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RailwayState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_rawDesc = nil
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
