// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#include "messages.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace GRPCRailway {

inline constexpr Train::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{0u},
        train_state_{static_cast< ::GRPCRailway::ETrainState >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Train::Train(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct TrainDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TrainDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TrainDefaultTypeInternal() {}
  union {
    Train _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TrainDefaultTypeInternal _Train_default_instance_;

inline constexpr RailwayState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{},
        _id_cached_byte_size_{0},
        rail_num_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RailwayState::RailwayState(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RailwayStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RailwayStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RailwayStateDefaultTypeInternal() {}
  union {
    RailwayState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RailwayStateDefaultTypeInternal _RailwayState_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR Empty::Empty(::_pbi::ConstantInitialized) {}
struct EmptyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyDefaultTypeInternal() {}
  union {
    Empty _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyDefaultTypeInternal _Empty_default_instance_;
}  // namespace GRPCRailway
static ::_pb::Metadata file_level_metadata_messages_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_messages_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_messages_2eproto = nullptr;
const ::uint32_t TableStruct_messages_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::RailwayState, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::RailwayState, _impl_.rail_num_),
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::RailwayState, _impl_.id_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::Empty, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::Train, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::Train, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::Train, _impl_.train_state_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::GRPCRailway::RailwayState)},
        {10, -1, -1, sizeof(::GRPCRailway::Empty)},
        {18, -1, -1, sizeof(::GRPCRailway::Train)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::GRPCRailway::_RailwayState_default_instance_._instance,
    &::GRPCRailway::_Empty_default_instance_._instance,
    &::GRPCRailway::_Train_default_instance_._instance,
};
const char descriptor_table_protodef_messages_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016messages.proto\022\013GRPCRailway\",\n\014Railway"
    "State\022\020\n\010rail_num\030\001 \001(\r\022\n\n\002id\030\002 \003(\r\"\007\n\005E"
    "mpty\"B\n\005Train\022\n\n\002id\030\001 \001(\r\022-\n\013train_state"
    "\030\002 \001(\0162\030.GRPCRailway.ETrainState*E\n\013ETra"
    "inState\022\013\n\007IN_TRIP\020\000\022\014\n\010IN_QUEUE\020\001\022\013\n\007AR"
    "RIVED\020\002\022\016\n\nDEPARTURED\020\0032\203\001\n\007Railway\022B\n\017G"
    "etRailwayState\022\022.GRPCRailway.Empty\032\031.GRP"
    "CRailway.RailwayState\"\000\0224\n\010GetTrain\022\022.GR"
    "PCRailway.Train\032\022.GRPCRailway.Train\"\000b\006p"
    "roto3"
};
static ::absl::once_flag descriptor_table_messages_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_messages_2eproto = {
    false,
    false,
    365,
    descriptor_table_protodef_messages_2eproto,
    "messages.proto",
    &descriptor_table_messages_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_messages_2eproto::offsets,
    file_level_metadata_messages_2eproto,
    file_level_enum_descriptors_messages_2eproto,
    file_level_service_descriptors_messages_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_messages_2eproto_getter() {
  return &descriptor_table_messages_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_messages_2eproto(&descriptor_table_messages_2eproto);
namespace GRPCRailway {
const ::google::protobuf::EnumDescriptor* ETrainState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_messages_2eproto);
  return file_level_enum_descriptors_messages_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ETrainState_internal_data_[] = {
    262144u, 0u, };
bool ETrainState_IsValid(int value) {
  return 0 <= value && value <= 3;
}
// ===================================================================

class RailwayState::_Internal {
 public:
};

RailwayState::RailwayState(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GRPCRailway.RailwayState)
}
inline PROTOBUF_NDEBUG_INLINE RailwayState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : id_{visibility, arena, from.id_},
        _id_cached_byte_size_{0},
        _cached_size_{0} {}

RailwayState::RailwayState(
    ::google::protobuf::Arena* arena,
    const RailwayState& from)
    : ::google::protobuf::Message(arena) {
  RailwayState* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.rail_num_ = from._impl_.rail_num_;

  // @@protoc_insertion_point(copy_constructor:GRPCRailway.RailwayState)
}
inline PROTOBUF_NDEBUG_INLINE RailwayState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : id_{visibility, arena},
        _id_cached_byte_size_{0},
        _cached_size_{0} {}

inline void RailwayState::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.rail_num_ = {};
}
RailwayState::~RailwayState() {
  // @@protoc_insertion_point(destructor:GRPCRailway.RailwayState)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RailwayState::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RailwayState::Clear() {
// @@protoc_insertion_point(message_clear_start:GRPCRailway.RailwayState)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.Clear();
  _impl_.rail_num_ = 0u;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RailwayState::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> RailwayState::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RailwayState_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated uint32 id = 2;
    {::_pbi::TcParser::FastV32P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RailwayState, _impl_.id_)}},
    // uint32 rail_num = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RailwayState, _impl_.rail_num_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RailwayState, _impl_.rail_num_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 rail_num = 1;
    {PROTOBUF_FIELD_OFFSET(RailwayState, _impl_.rail_num_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // repeated uint32 id = 2;
    {PROTOBUF_FIELD_OFFSET(RailwayState, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* RailwayState::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GRPCRailway.RailwayState)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 rail_num = 1;
  if (this->_internal_rail_num() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_rail_num(), target);
  }

  // repeated uint32 id = 2;
  {
    int byte_size = _impl_._id_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          2, _internal_id(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GRPCRailway.RailwayState)
  return target;
}

::size_t RailwayState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GRPCRailway.RailwayState)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint32 id = 2;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::UInt32Size(
        this->_internal_id())
    ;
    _impl_._id_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // uint32 rail_num = 1;
  if (this->_internal_rail_num() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_rail_num());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RailwayState::_class_data_ = {
    RailwayState::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RailwayState::GetClassData() const {
  return &_class_data_;
}

void RailwayState::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RailwayState*>(&to_msg);
  auto& from = static_cast<const RailwayState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GRPCRailway.RailwayState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_id()->MergeFrom(from._internal_id());
  if (from._internal_rail_num() != 0) {
    _this->_internal_set_rail_num(from._internal_rail_num());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RailwayState::CopyFrom(const RailwayState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GRPCRailway.RailwayState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RailwayState::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RailwayState::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RailwayState::InternalSwap(RailwayState* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.id_.InternalSwap(&other->_impl_.id_);
        swap(_impl_.rail_num_, other->_impl_.rail_num_);
}

::google::protobuf::Metadata RailwayState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messages_2eproto_getter, &descriptor_table_messages_2eproto_once,
      file_level_metadata_messages_2eproto[0]);
}
// ===================================================================

class Empty::_Internal {
 public:
};

Empty::Empty(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:GRPCRailway.Empty)
}
Empty::Empty(
    ::google::protobuf::Arena* arena,
    const Empty& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  Empty* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:GRPCRailway.Empty)
}









::google::protobuf::Metadata Empty::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messages_2eproto_getter, &descriptor_table_messages_2eproto_once,
      file_level_metadata_messages_2eproto[1]);
}
// ===================================================================

class Train::_Internal {
 public:
};

Train::Train(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GRPCRailway.Train)
}
Train::Train(
    ::google::protobuf::Arena* arena, const Train& from)
    : Train(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Train::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Train::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, train_state_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::train_state_));
}
Train::~Train() {
  // @@protoc_insertion_point(destructor:GRPCRailway.Train)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Train::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Train::Clear() {
// @@protoc_insertion_point(message_clear_start:GRPCRailway.Train)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.train_state_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.train_state_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Train::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Train::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Train_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .GRPCRailway.ETrainState train_state = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Train, _impl_.train_state_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Train, _impl_.train_state_)}},
    // uint32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Train, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Train, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Train, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // .GRPCRailway.ETrainState train_state = 2;
    {PROTOBUF_FIELD_OFFSET(Train, _impl_.train_state_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* Train::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GRPCRailway.Train)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_id(), target);
  }

  // .GRPCRailway.ETrainState train_state = 2;
  if (this->_internal_train_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_train_state(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GRPCRailway.Train)
  return target;
}

::size_t Train::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GRPCRailway.Train)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_id());
  }

  // .GRPCRailway.ETrainState train_state = 2;
  if (this->_internal_train_state() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_train_state());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Train::_class_data_ = {
    Train::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Train::GetClassData() const {
  return &_class_data_;
}

void Train::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Train*>(&to_msg);
  auto& from = static_cast<const Train&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GRPCRailway.Train)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_train_state() != 0) {
    _this->_internal_set_train_state(from._internal_train_state());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Train::CopyFrom(const Train& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GRPCRailway.Train)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Train::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Train::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Train::InternalSwap(Train* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Train, _impl_.train_state_)
      + sizeof(Train::_impl_.train_state_)
      - PROTOBUF_FIELD_OFFSET(Train, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata Train::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messages_2eproto_getter, &descriptor_table_messages_2eproto_once,
      file_level_metadata_messages_2eproto[2]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace GRPCRailway
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
