// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#include "messages.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace GRPCRailway {

inline constexpr VirtualTrainTemplate::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : num_{0u},
        time_interval_min_{0u},
        time_interval_max_{0u},
        time_to_stay_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR VirtualTrainTemplate::VirtualTrainTemplate(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct VirtualTrainTemplateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VirtualTrainTemplateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VirtualTrainTemplateDefaultTypeInternal() {}
  union {
    VirtualTrainTemplate _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VirtualTrainTemplateDefaultTypeInternal _VirtualTrainTemplate_default_instance_;

inline constexpr Train::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0u},
        wagons_{0u},
        lateness_{::uint64_t{0u}},
        train_state_{static_cast< ::GRPCRailway::ETrainState >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Train::Train(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct TrainDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TrainDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TrainDefaultTypeInternal() {}
  union {
    Train _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TrainDefaultTypeInternal _Train_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR Empty::Empty(::_pbi::ConstantInitialized) {}
struct EmptyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyDefaultTypeInternal() {}
  union {
    Empty _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyDefaultTypeInternal _Empty_default_instance_;

inline constexpr TrainArray::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : train_array_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TrainArray::TrainArray(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct TrainArrayDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TrainArrayDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TrainArrayDefaultTypeInternal() {}
  union {
    TrainArray _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TrainArrayDefaultTypeInternal _TrainArray_default_instance_;

inline constexpr RailwayState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : trains_{},
        rail_num_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RailwayState::RailwayState(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RailwayStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RailwayStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RailwayStateDefaultTypeInternal() {}
  union {
    RailwayState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RailwayStateDefaultTypeInternal _RailwayState_default_instance_;
}  // namespace GRPCRailway
static ::_pb::Metadata file_level_metadata_messages_2eproto[5];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_messages_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_messages_2eproto = nullptr;
const ::uint32_t TableStruct_messages_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::VirtualTrainTemplate, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::VirtualTrainTemplate, _impl_.num_),
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::VirtualTrainTemplate, _impl_.time_interval_min_),
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::VirtualTrainTemplate, _impl_.time_interval_max_),
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::VirtualTrainTemplate, _impl_.time_to_stay_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::TrainArray, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::TrainArray, _impl_.train_array_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::Train, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::Train, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::Train, _impl_.name_),
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::Train, _impl_.wagons_),
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::Train, _impl_.lateness_),
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::Train, _impl_.train_state_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::RailwayState, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::RailwayState, _impl_.rail_num_),
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::RailwayState, _impl_.trains_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::GRPCRailway::Empty, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::GRPCRailway::VirtualTrainTemplate)},
        {12, -1, -1, sizeof(::GRPCRailway::TrainArray)},
        {21, -1, -1, sizeof(::GRPCRailway::Train)},
        {34, -1, -1, sizeof(::GRPCRailway::RailwayState)},
        {44, -1, -1, sizeof(::GRPCRailway::Empty)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::GRPCRailway::_VirtualTrainTemplate_default_instance_._instance,
    &::GRPCRailway::_TrainArray_default_instance_._instance,
    &::GRPCRailway::_Train_default_instance_._instance,
    &::GRPCRailway::_RailwayState_default_instance_._instance,
    &::GRPCRailway::_Empty_default_instance_._instance,
};
const char descriptor_table_protodef_messages_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016messages.proto\022\013GRPCRailway\"o\n\024Virtual"
    "TrainTemplate\022\013\n\003num\030\001 \001(\r\022\031\n\021time_inter"
    "val_min\030\002 \001(\r\022\031\n\021time_interval_max\030\003 \001(\r"
    "\022\024\n\014time_to_stay\030\004 \001(\r\"5\n\nTrainArray\022\'\n\013"
    "train_array\030\001 \003(\0132\022.GRPCRailway.Train\"r\n"
    "\005Train\022\n\n\002id\030\001 \001(\r\022\014\n\004name\030\002 \001(\t\022\016\n\006wago"
    "ns\030\003 \001(\r\022\020\n\010lateness\030\004 \001(\004\022-\n\013train_stat"
    "e\030\005 \001(\0162\030.GRPCRailway.ETrainState\"D\n\014Rai"
    "lwayState\022\020\n\010rail_num\030\001 \001(\r\022\"\n\006trains\030\002 "
    "\003(\0132\022.GRPCRailway.Train\"\007\n\005Empty*W\n\013ETra"
    "inState\022\013\n\007IN_TRIP\020\000\022\014\n\010IN_QUEUE\020\001\022\013\n\007AR"
    "RIVED\020\002\022\016\n\nDEPARTURED\020\003\022\020\n\014IN_TRIP_LATE\020"
    "\0042\221\003\n\007Railway\022B\n\017GetRailwayState\022\022.GRPCR"
    "ailway.Empty\032\031.GRPCRailway.RailwayState\""
    "\000\0224\n\010GetTrain\022\022.GRPCRailway.Train\032\022.GRPC"
    "Railway.Train\"\000\022@\n\017GetTrainInQueue\022\022.GRP"
    "CRailway.Empty\032\027.GRPCRailway.TrainArray\""
    "\000\022<\n\013GetAllTrain\022\022.GRPCRailway.Empty\032\027.G"
    "RPCRailway.TrainArray\"\000\022\?\n\016GetTrainOnRai"
    "l\022\022.GRPCRailway.Empty\032\027.GRPCRailway.Trai"
    "nArray\"\000\022K\n\020AddVirtualTrains\022!.GRPCRailw"
    "ay.VirtualTrainTemplate\032\022.GRPCRailway.Em"
    "pty\"\000B\"Z http_railway_server/railway_grp"
    "cb\006proto3"
};
static ::absl::once_flag descriptor_table_messages_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_messages_2eproto = {
    false,
    false,
    929,
    descriptor_table_protodef_messages_2eproto,
    "messages.proto",
    &descriptor_table_messages_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_messages_2eproto::offsets,
    file_level_metadata_messages_2eproto,
    file_level_enum_descriptors_messages_2eproto,
    file_level_service_descriptors_messages_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_messages_2eproto_getter() {
  return &descriptor_table_messages_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_messages_2eproto(&descriptor_table_messages_2eproto);
namespace GRPCRailway {
const ::google::protobuf::EnumDescriptor* ETrainState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_messages_2eproto);
  return file_level_enum_descriptors_messages_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ETrainState_internal_data_[] = {
    327680u, 0u, };
bool ETrainState_IsValid(int value) {
  return 0 <= value && value <= 4;
}
// ===================================================================

class VirtualTrainTemplate::_Internal {
 public:
};

VirtualTrainTemplate::VirtualTrainTemplate(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GRPCRailway.VirtualTrainTemplate)
}
VirtualTrainTemplate::VirtualTrainTemplate(
    ::google::protobuf::Arena* arena, const VirtualTrainTemplate& from)
    : VirtualTrainTemplate(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE VirtualTrainTemplate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void VirtualTrainTemplate::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, num_),
           0,
           offsetof(Impl_, time_to_stay_) -
               offsetof(Impl_, num_) +
               sizeof(Impl_::time_to_stay_));
}
VirtualTrainTemplate::~VirtualTrainTemplate() {
  // @@protoc_insertion_point(destructor:GRPCRailway.VirtualTrainTemplate)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void VirtualTrainTemplate::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void VirtualTrainTemplate::Clear() {
// @@protoc_insertion_point(message_clear_start:GRPCRailway.VirtualTrainTemplate)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.num_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.time_to_stay_) -
      reinterpret_cast<char*>(&_impl_.num_)) + sizeof(_impl_.time_to_stay_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* VirtualTrainTemplate::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> VirtualTrainTemplate::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_VirtualTrainTemplate_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // uint32 time_to_stay = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VirtualTrainTemplate, _impl_.time_to_stay_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(VirtualTrainTemplate, _impl_.time_to_stay_)}},
    // uint32 num = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VirtualTrainTemplate, _impl_.num_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(VirtualTrainTemplate, _impl_.num_)}},
    // uint32 time_interval_min = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VirtualTrainTemplate, _impl_.time_interval_min_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(VirtualTrainTemplate, _impl_.time_interval_min_)}},
    // uint32 time_interval_max = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VirtualTrainTemplate, _impl_.time_interval_max_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(VirtualTrainTemplate, _impl_.time_interval_max_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 num = 1;
    {PROTOBUF_FIELD_OFFSET(VirtualTrainTemplate, _impl_.num_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 time_interval_min = 2;
    {PROTOBUF_FIELD_OFFSET(VirtualTrainTemplate, _impl_.time_interval_min_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 time_interval_max = 3;
    {PROTOBUF_FIELD_OFFSET(VirtualTrainTemplate, _impl_.time_interval_max_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 time_to_stay = 4;
    {PROTOBUF_FIELD_OFFSET(VirtualTrainTemplate, _impl_.time_to_stay_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* VirtualTrainTemplate::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GRPCRailway.VirtualTrainTemplate)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 num = 1;
  if (this->_internal_num() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_num(), target);
  }

  // uint32 time_interval_min = 2;
  if (this->_internal_time_interval_min() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_time_interval_min(), target);
  }

  // uint32 time_interval_max = 3;
  if (this->_internal_time_interval_max() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_time_interval_max(), target);
  }

  // uint32 time_to_stay = 4;
  if (this->_internal_time_to_stay() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this->_internal_time_to_stay(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GRPCRailway.VirtualTrainTemplate)
  return target;
}

::size_t VirtualTrainTemplate::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GRPCRailway.VirtualTrainTemplate)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 num = 1;
  if (this->_internal_num() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_num());
  }

  // uint32 time_interval_min = 2;
  if (this->_internal_time_interval_min() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_time_interval_min());
  }

  // uint32 time_interval_max = 3;
  if (this->_internal_time_interval_max() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_time_interval_max());
  }

  // uint32 time_to_stay = 4;
  if (this->_internal_time_to_stay() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_time_to_stay());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData VirtualTrainTemplate::_class_data_ = {
    VirtualTrainTemplate::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* VirtualTrainTemplate::GetClassData() const {
  return &_class_data_;
}

void VirtualTrainTemplate::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<VirtualTrainTemplate*>(&to_msg);
  auto& from = static_cast<const VirtualTrainTemplate&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GRPCRailway.VirtualTrainTemplate)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_num() != 0) {
    _this->_internal_set_num(from._internal_num());
  }
  if (from._internal_time_interval_min() != 0) {
    _this->_internal_set_time_interval_min(from._internal_time_interval_min());
  }
  if (from._internal_time_interval_max() != 0) {
    _this->_internal_set_time_interval_max(from._internal_time_interval_max());
  }
  if (from._internal_time_to_stay() != 0) {
    _this->_internal_set_time_to_stay(from._internal_time_to_stay());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void VirtualTrainTemplate::CopyFrom(const VirtualTrainTemplate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GRPCRailway.VirtualTrainTemplate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool VirtualTrainTemplate::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* VirtualTrainTemplate::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void VirtualTrainTemplate::InternalSwap(VirtualTrainTemplate* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VirtualTrainTemplate, _impl_.time_to_stay_)
      + sizeof(VirtualTrainTemplate::_impl_.time_to_stay_)
      - PROTOBUF_FIELD_OFFSET(VirtualTrainTemplate, _impl_.num_)>(
          reinterpret_cast<char*>(&_impl_.num_),
          reinterpret_cast<char*>(&other->_impl_.num_));
}

::google::protobuf::Metadata VirtualTrainTemplate::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messages_2eproto_getter, &descriptor_table_messages_2eproto_once,
      file_level_metadata_messages_2eproto[0]);
}
// ===================================================================

class TrainArray::_Internal {
 public:
};

TrainArray::TrainArray(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GRPCRailway.TrainArray)
}
inline PROTOBUF_NDEBUG_INLINE TrainArray::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : train_array_{visibility, arena, from.train_array_},
        _cached_size_{0} {}

TrainArray::TrainArray(
    ::google::protobuf::Arena* arena,
    const TrainArray& from)
    : ::google::protobuf::Message(arena) {
  TrainArray* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:GRPCRailway.TrainArray)
}
inline PROTOBUF_NDEBUG_INLINE TrainArray::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : train_array_{visibility, arena},
        _cached_size_{0} {}

inline void TrainArray::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
TrainArray::~TrainArray() {
  // @@protoc_insertion_point(destructor:GRPCRailway.TrainArray)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void TrainArray::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void TrainArray::Clear() {
// @@protoc_insertion_point(message_clear_start:GRPCRailway.TrainArray)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.train_array_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* TrainArray::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> TrainArray::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_TrainArray_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .GRPCRailway.Train train_array = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TrainArray, _impl_.train_array_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .GRPCRailway.Train train_array = 1;
    {PROTOBUF_FIELD_OFFSET(TrainArray, _impl_.train_array_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::GRPCRailway::Train>()},
  }}, {{
  }},
};

::uint8_t* TrainArray::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GRPCRailway.TrainArray)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .GRPCRailway.Train train_array = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_train_array_size()); i < n; i++) {
    const auto& repfield = this->_internal_train_array().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GRPCRailway.TrainArray)
  return target;
}

::size_t TrainArray::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GRPCRailway.TrainArray)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .GRPCRailway.Train train_array = 1;
  total_size += 1UL * this->_internal_train_array_size();
  for (const auto& msg : this->_internal_train_array()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData TrainArray::_class_data_ = {
    TrainArray::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* TrainArray::GetClassData() const {
  return &_class_data_;
}

void TrainArray::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<TrainArray*>(&to_msg);
  auto& from = static_cast<const TrainArray&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GRPCRailway.TrainArray)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_train_array()->MergeFrom(
      from._internal_train_array());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TrainArray::CopyFrom(const TrainArray& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GRPCRailway.TrainArray)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool TrainArray::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* TrainArray::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void TrainArray::InternalSwap(TrainArray* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.train_array_.InternalSwap(&other->_impl_.train_array_);
}

::google::protobuf::Metadata TrainArray::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messages_2eproto_getter, &descriptor_table_messages_2eproto_once,
      file_level_metadata_messages_2eproto[1]);
}
// ===================================================================

class Train::_Internal {
 public:
};

Train::Train(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GRPCRailway.Train)
}
inline PROTOBUF_NDEBUG_INLINE Train::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        _cached_size_{0} {}

Train::Train(
    ::google::protobuf::Arena* arena,
    const Train& from)
    : ::google::protobuf::Message(arena) {
  Train* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, train_state_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::train_state_));

  // @@protoc_insertion_point(copy_constructor:GRPCRailway.Train)
}
inline PROTOBUF_NDEBUG_INLINE Train::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void Train::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, train_state_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::train_state_));
}
Train::~Train() {
  // @@protoc_insertion_point(destructor:GRPCRailway.Train)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Train::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Train::Clear() {
// @@protoc_insertion_point(message_clear_start:GRPCRailway.Train)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.train_state_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.train_state_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Train::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 30, 2> Train::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Train_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Train, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Train, _impl_.id_)}},
    // string name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Train, _impl_.name_)}},
    // uint32 wagons = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Train, _impl_.wagons_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Train, _impl_.wagons_)}},
    // uint64 lateness = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Train, _impl_.lateness_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(Train, _impl_.lateness_)}},
    // .GRPCRailway.ETrainState train_state = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Train, _impl_.train_state_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(Train, _impl_.train_state_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Train, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string name = 2;
    {PROTOBUF_FIELD_OFFSET(Train, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 wagons = 3;
    {PROTOBUF_FIELD_OFFSET(Train, _impl_.wagons_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint64 lateness = 4;
    {PROTOBUF_FIELD_OFFSET(Train, _impl_.lateness_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // .GRPCRailway.ETrainState train_state = 5;
    {PROTOBUF_FIELD_OFFSET(Train, _impl_.train_state_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\21\0\4\0\0\0\0\0"
    "GRPCRailway.Train"
    "name"
  }},
};

::uint8_t* Train::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GRPCRailway.Train)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_id(), target);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GRPCRailway.Train.name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // uint32 wagons = 3;
  if (this->_internal_wagons() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_wagons(), target);
  }

  // uint64 lateness = 4;
  if (this->_internal_lateness() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        4, this->_internal_lateness(), target);
  }

  // .GRPCRailway.ETrainState train_state = 5;
  if (this->_internal_train_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        5, this->_internal_train_state(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GRPCRailway.Train)
  return target;
}

::size_t Train::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GRPCRailway.Train)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // uint32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_id());
  }

  // uint32 wagons = 3;
  if (this->_internal_wagons() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_wagons());
  }

  // uint64 lateness = 4;
  if (this->_internal_lateness() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_lateness());
  }

  // .GRPCRailway.ETrainState train_state = 5;
  if (this->_internal_train_state() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_train_state());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Train::_class_data_ = {
    Train::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Train::GetClassData() const {
  return &_class_data_;
}

void Train::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Train*>(&to_msg);
  auto& from = static_cast<const Train&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GRPCRailway.Train)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_wagons() != 0) {
    _this->_internal_set_wagons(from._internal_wagons());
  }
  if (from._internal_lateness() != 0) {
    _this->_internal_set_lateness(from._internal_lateness());
  }
  if (from._internal_train_state() != 0) {
    _this->_internal_set_train_state(from._internal_train_state());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Train::CopyFrom(const Train& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GRPCRailway.Train)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Train::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Train::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Train::InternalSwap(Train* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Train, _impl_.train_state_)
      + sizeof(Train::_impl_.train_state_)
      - PROTOBUF_FIELD_OFFSET(Train, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata Train::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messages_2eproto_getter, &descriptor_table_messages_2eproto_once,
      file_level_metadata_messages_2eproto[2]);
}
// ===================================================================

class RailwayState::_Internal {
 public:
};

RailwayState::RailwayState(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GRPCRailway.RailwayState)
}
inline PROTOBUF_NDEBUG_INLINE RailwayState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : trains_{visibility, arena, from.trains_},
        _cached_size_{0} {}

RailwayState::RailwayState(
    ::google::protobuf::Arena* arena,
    const RailwayState& from)
    : ::google::protobuf::Message(arena) {
  RailwayState* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.rail_num_ = from._impl_.rail_num_;

  // @@protoc_insertion_point(copy_constructor:GRPCRailway.RailwayState)
}
inline PROTOBUF_NDEBUG_INLINE RailwayState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : trains_{visibility, arena},
        _cached_size_{0} {}

inline void RailwayState::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.rail_num_ = {};
}
RailwayState::~RailwayState() {
  // @@protoc_insertion_point(destructor:GRPCRailway.RailwayState)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RailwayState::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RailwayState::Clear() {
// @@protoc_insertion_point(message_clear_start:GRPCRailway.RailwayState)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.trains_.Clear();
  _impl_.rail_num_ = 0u;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RailwayState::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> RailwayState::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_RailwayState_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .GRPCRailway.Train trains = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RailwayState, _impl_.trains_)}},
    // uint32 rail_num = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RailwayState, _impl_.rail_num_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RailwayState, _impl_.rail_num_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 rail_num = 1;
    {PROTOBUF_FIELD_OFFSET(RailwayState, _impl_.rail_num_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // repeated .GRPCRailway.Train trains = 2;
    {PROTOBUF_FIELD_OFFSET(RailwayState, _impl_.trains_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::GRPCRailway::Train>()},
  }}, {{
  }},
};

::uint8_t* RailwayState::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GRPCRailway.RailwayState)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 rail_num = 1;
  if (this->_internal_rail_num() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_rail_num(), target);
  }

  // repeated .GRPCRailway.Train trains = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_trains_size()); i < n; i++) {
    const auto& repfield = this->_internal_trains().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GRPCRailway.RailwayState)
  return target;
}

::size_t RailwayState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GRPCRailway.RailwayState)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .GRPCRailway.Train trains = 2;
  total_size += 1UL * this->_internal_trains_size();
  for (const auto& msg : this->_internal_trains()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // uint32 rail_num = 1;
  if (this->_internal_rail_num() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_rail_num());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RailwayState::_class_data_ = {
    RailwayState::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RailwayState::GetClassData() const {
  return &_class_data_;
}

void RailwayState::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RailwayState*>(&to_msg);
  auto& from = static_cast<const RailwayState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GRPCRailway.RailwayState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_trains()->MergeFrom(
      from._internal_trains());
  if (from._internal_rail_num() != 0) {
    _this->_internal_set_rail_num(from._internal_rail_num());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RailwayState::CopyFrom(const RailwayState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GRPCRailway.RailwayState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RailwayState::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RailwayState::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RailwayState::InternalSwap(RailwayState* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.trains_.InternalSwap(&other->_impl_.trains_);
        swap(_impl_.rail_num_, other->_impl_.rail_num_);
}

::google::protobuf::Metadata RailwayState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messages_2eproto_getter, &descriptor_table_messages_2eproto_once,
      file_level_metadata_messages_2eproto[3]);
}
// ===================================================================

class Empty::_Internal {
 public:
};

Empty::Empty(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:GRPCRailway.Empty)
}
Empty::Empty(
    ::google::protobuf::Arena* arena,
    const Empty& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  Empty* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:GRPCRailway.Empty)
}









::google::protobuf::Metadata Empty::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messages_2eproto_getter, &descriptor_table_messages_2eproto_once,
      file_level_metadata_messages_2eproto[4]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace GRPCRailway
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
